version: '3'                        # docker-compose file format. Ex. 1, 2, or 3.
                                    # Different versions work with different versions of Docker, and support different features

services:                           # Configs for the various services, we just have one
  jekyll:
    image: jekyll/jekyll:4.2.0     # Image name to pull from Docker Hub
    command: jekyll serve --livereload     # Command to run when the container starts
    ports:
      - 4000:4000                   # Map local port 4000 to port 4000 in the container
      - 35729:35729                 # We need to specify another port for the Jekyll 3.70+ live reload feature
    volumes:
      - ./docs:/srv/jekyll 