title: Mike Alves
email: michelalvs@gmail.com
description: |-
  Esse é meu site estático feito com Jekyll.
url: ""
github_username: mikxingu
instagram_username: mikeriderbr
theme: minima
plugins:
  - jekyll-feed
  - jekyll-admin
  - jekyll-default-layout
